<?php

/**
 * MageFlow
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@mageflow.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * If you wish to use the MageFlow Connect extension as part of a paid
 * service please contact licence@mageflow.com for information about
 * obtaining an appropriate licence.
 */

/**
 * Html.php
 *
 * PHP version 5
 *
 * @category   MFX
 * @package    Mageflow_Connect
 * @subpackage Model
 * @author     MageFlow OÜ, Estonia <info@mageflow.com>
 * @copyright  Copyright (C) 2014 MageFlow OÜ, Estonia (http://mageflow.com) 
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link       http://mageflow.com/
 */

/**
 * Mageflow_Connect_Model_Api2_Renderer_Html
 * Webservice API2 renderer of HTML type model
 *
 * @category   MFX
 * @package    Mageflow_Connect
 * @subpackage Model
 * @author     MageFlow OÜ, Estonia <info@mageflow.com>
 * @copyright  Copyright (C) 2014 MageFlow OÜ, Estonia (http://mageflow.com) 
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link       http://mageflow.com/
 */
class Mageflow_Connect_Model_Api2_Renderer_Html
    implements Mage_Api2_Model_Renderer_Interface
{
    /**
     * Adapter mime type
     */
    const MIME_TYPE = 'text/html';

    /**
     * Render API resource as HTML
     *
     * @param mixed $data
     *
     * @return string
     */
    public function render($data)
    {
        $content = $this->_renderArray($data);
        $html
            = <<<HTML
<html>
<head>
    <title>MageFlow API documentation</title>
    <style type="text/css">
        body{
            font-family: sans-serif;
            font-size: 12px;
        }
    </style>
</head>
<body>
$content
</body>
</html>
HTML;
        return $html;
    }


    /**
     * Renders array elements to HTML
     *
     * @param \Mage_Core_Model_Config_Element $data
     *
     * @return string
     */
    private function _renderArray($data)
    {
        $html = "<h2>API Resources</h2>";
        $html .= '<ul>';
        if ($data instanceof Mage_Core_Model_Config_Element) {
            foreach ($data->children() as $name => $element) {
                $html .= sprintf("\t<li>\n%s\n", $name);
                $html .= "<ul>\n";
                foreach ($element->routes->children() as $routeEntity) {
                    $html .= sprintf(
                        "\t\t<li>
                        <a href='/api/rest%1\$s'>/api/rest%1\$s</a>
                        </li>\n",
                        $routeEntity->route
                    );
                }
                $html .= "</ul>\n";
                $html .= "\t</li>\n";
            }
        }
        $html .= '</ul>';
        return $html;
    }

    /**
     * Get MIME type generated by renderer
     *
     * @return string
     */
    public function getMimeType()
    {
        return self::MIME_TYPE;
    }
}
